[package]
name = "mcman"
version = "0.1.2"
edition = "2024"

description = "Minecraft Server Console with autocomplete"
repository = "https://github.com/mavenried/mcman"
authors = ["Joseph Chacko <josephchacko2006@gmail.com>"]
license = "MIT OR Apache-2.0"
keywords = ["minecraft", "console"]

[dependencies]
ratatui = "0.29"
crossterm = { version = "0.28", features = ["event-stream"] }
unicode-width = "0.2.0"
