pub const COMMANDS: &[(&str, &[&str])] = &[
    ("advancement", &["grant", "revoke"]),
    ("attribute", &[]),
    ("ban", &[]),
    ("ban-ip", &[]),
    ("banlist", &["ips", "players"]),
    ("bossbar", &["add", "remove", "list", "set", "get"]),
    ("clear", &[]),
    ("clone", &["from"]),
    ("damage", &[]),
    ("data", &["merge", "get", "remove", "modify"]),
    ("datapack", &["enable", "disable", "list", "create"]),
    ("debug", &["start", "stop", "function"]),
    (
        "defaultgamemode",
        &["survival", "creative", "adventure", "spectator"],
    ),
    ("deop", &[]),
    ("dialog", &["show", "clear"]),
    ("difficulty", &["peaceful", "easy", "normal", "hard"]),
    ("effect", &["clear", "give"]),
    ("enchant", &[]),
    (
        "execute",
        &[
            "run",
            "if",
            "unless",
            "as",
            "at",
            "store",
            "positioned",
            "rotated",
            "facing",
            "align",
            "anchored",
            "in",
            "summon",
            "on",
        ],
    ),
    ("experience", &["add", "set", "query"]),
    (
        "fill",
        &["outline", "hollow", "destroy", "strict", "replace", "keep"],
    ),
    ("fillbiome", &["replace"]),
    ("forceload", &["add", "remove", "query"]),
    ("function", &["with"]),
    (
        "gamemode",
        &["survival", "creative", "adventure", "spectator"],
    ),
    (
        "gamerule",
        &[
            "advance_time",
            "advance_weather",
            "block_drops",
            "block_explosion_drop_decay",
            "command_block_output",
            "command_blocks_work",
            "drowning_damage",
            "elytra_movement_check",
            "ender_pearls_vanish_on_death",
            "entity_drops",
            "fall_damage",
            "fire_damage",
            "fire_spread_radius_around_player",
            "forgive_dead_players",
            "freeze_damage",
            "global_sound_events",
            "immediate_respawn",
            "keep_inventory",
            "lava_source_conversion",
            "limited_crafting",
            "locator_bar",
            "log_admin_commands",
            "max_block_modifications",
            "max_command_forks",
            "max_command_sequence_length",
            "max_entity_cramming",
            "max_snow_accumulation_height",
            "mob_drops",
            "mob_explosion_drop_decay",
            "mob_griefing",
            "natural_health_regeneration",
            "player_movement_check",
            "players_nether_portal_creative_delay",
            "players_nether_portal_default_delay",
            "players_sleeping_percentage",
            "projectiles_can_break_blocks",
            "pvp",
            "raids",
            "random_tick_speed",
            "reduced_debug_info",
            "respawn_radius",
            "send_command_feedback",
            "show_advancement_messages",
            "show_death_messages",
            "spawn_mobs",
            "spawn_monsters",
            "spawn_patrols",
            "spawn_phantoms",
            "spawn_wandering_traders",
            "spawn_wardens",
            "spawner_blocks_work",
            "spectators_generate_chunks",
            "spread_vines",
            "tnt_explodes",
            "tnt_explosion_drop_decay",
            "universal_anger",
            "water_source_conversion",
        ],
    ),
    ("give", &[]),
    ("help", &[]),
    ("item", &["replace", "modify"]),
    ("jfr", &["start", "stop"]),
    ("kick", &[]),
    ("kill", &[]),
    ("list", &["uuids"]),
    ("locate", &["structure", "biome", "poi"]),
    ("loot", &["replace", "insert", "give", "spawn"]),
    ("me", &[]),
    ("msg", &[]),
    ("op", &[]),
    ("pardon", &[]),
    ("pardon-ip", &[]),
    ("particle", &[]),
    ("perf", &["start", "stop"]),
    ("place", &["feature", "jigsaw", "structure", "template"]),
    (
        "playsound",
        &[
            "master", "music", "record", "weather", "block", "hostile", "neutral", "player",
            "ambient", "voice", "ui",
        ],
    ),
    ("random", &["value", "roll", "reset"]),
    ("recipe", &["give", "take"]),
    ("reload", &[]),
    ("return", &["fail", "run"]),
    ("ride", &["mount", "dismount"]),
    ("rotate", &["facing"]),
    ("save-all", &["flush"]),
    ("save-off", &[]),
    ("save-on", &[]),
    ("say", &[]),
    ("schedule", &["function", "clear"]),
    ("scoreboard", &["objectives", "players"]),
    ("seed", &[]),
    ("setblock", &["destroy", "keep", "replace", "strict"]),
    ("setidletimeout", &[]),
    ("setworldspawn", &[]),
    ("spectate", &[]),
    ("spreadplayers", &["respectTeams", "under"]),
    ("spawnpoint", &[]),
    ("stop", &[]),
    ("stopwatch", &["create", "query", "restart", "remove"]),
    (
        "stopsound",
        &[
            "*", "master", "music", "record", "weather", "block", "hostile", "neutral", "player",
            "ambient", "voice", "ui",
        ],
    ),
    ("summon", &[]),
    ("tag", &["add", "remove", "list"]),
    (
        "team",
        &["list", "add", "remove", "empty", "join", "leave", "modify"],
    ),
    ("teammsg", &[]),
    ("teleport", &[]),
    ("tellraw", &[]),
    (
        "test",
        &[
            "run",
            "runmultiple",
            "runthese",
            "runclosest",
            "runthat",
            "runfailed",
            "verify",
            "locate",
            "resetclosest",
            "resetthese",
            "resetthat",
            "clearthat",
            "clearthese",
            "clearall",
            "stop",
            "pos",
            "create",
        ],
    ),
    (
        "tick",
        &["query", "rate", "step", "sprint", "unfreeze", "freeze"],
    ),
    (
        "time",
        &["set", "add", "pause", "resume", "rate", "query", "of"],
    ),
    (
        "title",
        &["clear", "reset", "title", "subtitle", "actionbar", "times"],
    ),
    ("tp", &[]),
    ("transfer", &[]),
    ("trigger", &["add", "set"]),
    ("version", &[]),
    ("waypoint", &["list", "modify"]),
    ("weather", &["clear", "rain", "thunder"]),
    (
        "whitelist",
        &["on", "off", "list", "add", "remove", "reload"],
    ),
    (
        "worldborder",
        &["add", "set", "center", "damage", "get", "warning"],
    ),
    ("w", &[]),
    ("xp", &["add", "set", "query"]),
];
